- name: add azure subnetwork
  azure_rm_subnet:
    subscription_id: "{{ subscription_id }}"
    tenant: "{{ tenant_id }}"
    client_id: "{{ client_id}}"
    secret: "{{ client_secret }}"
    name: "{{ subnet_name }}"
    resource_group: "{{ resource_group }}"
    virtual_network: "{{ virtual_network }}"
    address_prefix_cidr: "{{ subnet_address_prefix_cidr }}"
  register: subnet_output

- name: display resource
  debug:
    msg: "{{ subnet_output }}"

- name: set subnet variable
  set_fact:
    subnet: "{{ subnet_output.state.name }}"
  when: subnet_output is defined

- name: display subnet resource
  debug:
    msg: "{{ subnet }}"
  when: subnet_output is defined
