- name: create azure resource group
  azure_rm_resourcegroup:
    subscription_id: "{{ subscription_id }}"
    tenant: "{{ tenant_id }}"
    client_id: "{{ client_id}}"
    secret: "{{ client_secret }}"
    name: "{{ resource_group_name }}"
    location: "{{ resource_group_location }}"
    state: present
  register: rg_output

- name: display resource
  debug:
    msg: "{{ rg_output }}"

- name: set resource_group variable
  set_fact:
    resource_group: "{{ rg_output.state.name }}"
  when: rg_output is defined

- name: display resource
  debug:
    msg: "{{ resource_group }}"
