- name: create azure network interface
  azure_rm_networkinterface:
    subscription_id: "{{ subscription_id }}"
    tenant: "{{ tenant_id }}"
    client_id: "{{ client_id}}"
    secret: "{{ client_secret }}"
    name: "{{ network_interface_name }}"
    resource_group: "{{ resource_group }}"
    virtual_network: "{{ virtual_network }}"
    subnet_name: "{{ subnet }}"
    create_with_security_group: false
    #security_group: 
    #  name: "{{ security_group }}"
    #  resource_group: "{{ resource_group }}"
    ip_configurations:
      - name: "{{ public_ip }}"
        public_ip_address_name: "{{ public_ip }}"
        primary: true
  register: nic_output

- name: display resource
  debug:
    msg: "{{ nic_output }}"

- name: set virtual_network variable
  set_fact:
    network_interface: "{{ nic_output.state.name }}"
  when: nic_output is defined

- name: display resource
  debug:
    msg: "{{ network_interface }}"
  when: nic_output is defined
